EXP_NUM="diligent100"
CUDA_NUM="0"
TESTING="False"
EXP_CODE="exp_01"
python train.py --config configs/$EXP_NUM/ball_pom.yml --cuda $CUDA_NUM --testing $TESTING --exp_code $EXP_CODE
python train.py --config configs/$EXP_NUM/ball_pp.yml --cuda $CUDA_NUM --testing $TESTING --exp_code $EXP_CODE
python train.py --config configs/$EXP_NUM/ball_acrylic.yml --cuda $CUDA_NUM --testing $TESTING --exp_code $EXP_CODE
python train.py --config configs/$EXP_NUM/ball_al.yml --cuda $CUDA_NUM --testing $TESTING --exp_code $EXP_CODE
python train.py --config configs/$EXP_NUM/ball_pvc.yml --cuda $CUDA_NUM --testing $TESTING --exp_code $EXP_CODE
python train.py --config configs/$EXP_NUM/ball_bakelite.yml --cuda $CUDA_NUM --testing $TESTING --exp_code $EXP_CODE
python train.py --config configs/$EXP_NUM/ball_cu.yml --cuda $CUDA_NUM --testing $TESTING --exp_code $EXP_CODE
python train.py --config configs/$EXP_NUM/ball_nylon.yml --cuda $CUDA_NUM --testing $TESTING --exp_code $EXP_CODE
python train.py --config configs/$EXP_NUM/ball_abs.yml --cuda $CUDA_NUM --testing $TESTING --exp_code $EXP_CODE
python train.py --config configs/$EXP_NUM/ball_steel.yml --cuda $CUDA_NUM --testing $TESTING --exp_code $EXP_CODE
python train.py --config configs/$EXP_NUM/golf_pom.yml --cuda $CUDA_NUM --testing $TESTING --exp_code $EXP_CODE
python train.py --config configs/$EXP_NUM/golf_pp.yml --cuda $CUDA_NUM --testing $TESTING --exp_code $EXP_CODE
python train.py --config configs/$EXP_NUM/golf_acrylic.yml --cuda $CUDA_NUM --testing $TESTING --exp_code $EXP_CODE
python train.py --config configs/$EXP_NUM/golf_al.yml --cuda $CUDA_NUM --testing $TESTING --exp_code $EXP_CODE
python train.py --config configs/$EXP_NUM/golf_pvc.yml --cuda $CUDA_NUM --testing $TESTING --exp_code $EXP_CODE
python train.py --config configs/$EXP_NUM/golf_bakelite.yml --cuda $CUDA_NUM --testing $TESTING --exp_code $EXP_CODE
python train.py --config configs/$EXP_NUM/golf_cu.yml --cuda $CUDA_NUM --testing $TESTING --exp_code $EXP_CODE
python train.py --config configs/$EXP_NUM/golf_nylon.yml --cuda $CUDA_NUM --testing $TESTING --exp_code $EXP_CODE
python train.py --config configs/$EXP_NUM/golf_abs.yml --cuda $CUDA_NUM --testing $TESTING --exp_code $EXP_CODE
python train.py --config configs/$EXP_NUM/golf_steel.yml --cuda $CUDA_NUM --testing $TESTING --exp_code $EXP_CODE
python train.py --config configs/$EXP_NUM/bunny_pom.yml --cuda $CUDA_NUM --testing $TESTING --exp_code $EXP_CODE
python train.py --config configs/$EXP_NUM/bunny_pp.yml --cuda $CUDA_NUM --testing $TESTING --exp_code $EXP_CODE
python train.py --config configs/$EXP_NUM/bunny_acrylic.yml --cuda $CUDA_NUM --testing $TESTING --exp_code $EXP_CODE
python train.py --config configs/$EXP_NUM/bunny_al.yml --cuda $CUDA_NUM --testing $TESTING --exp_code $EXP_CODE
python train.py --config configs/$EXP_NUM/bunny_pvc.yml --cuda $CUDA_NUM --testing $TESTING --exp_code $EXP_CODE
python train.py --config configs/$EXP_NUM/bunny_bakelite.yml --cuda $CUDA_NUM --testing $TESTING --exp_code $EXP_CODE
python train.py --config configs/$EXP_NUM/bunny_cu.yml --cuda $CUDA_NUM --testing $TESTING --exp_code $EXP_CODE
python train.py --config configs/$EXP_NUM/bunny_nylon.yml --cuda $CUDA_NUM --testing $TESTING --exp_code $EXP_CODE
python train.py --config configs/$EXP_NUM/bunny_abs.yml --cuda $CUDA_NUM --testing $TESTING --exp_code $EXP_CODE
python train.py --config configs/$EXP_NUM/bunny_steel.yml --cuda $CUDA_NUM --testing $TESTING --exp_code $EXP_CODE
python train.py --config configs/$EXP_NUM/hexagon_pom.yml --cuda $CUDA_NUM --testing $TESTING --exp_code $EXP_CODE
python train.py --config configs/$EXP_NUM/hexagon_pp.yml --cuda $CUDA_NUM --testing $TESTING --exp_code $EXP_CODE
python train.py --config configs/$EXP_NUM/hexagon_acrylic.yml --cuda $CUDA_NUM --testing $TESTING --exp_code $EXP_CODE
python train.py --config configs/$EXP_NUM/hexagon_al.yml --cuda $CUDA_NUM --testing $TESTING --exp_code $EXP_CODE
python train.py --config configs/$EXP_NUM/hexagon_pvc.yml --cuda $CUDA_NUM --testing $TESTING --exp_code $EXP_CODE
python train.py --config configs/$EXP_NUM/hexagon_bakelite.yml --cuda $CUDA_NUM --testing $TESTING --exp_code $EXP_CODE
python train.py --config configs/$EXP_NUM/hexagon_cu.yml --cuda $CUDA_NUM --testing $TESTING --exp_code $EXP_CODE
python train.py --config configs/$EXP_NUM/hexagon_nylon.yml --cuda $CUDA_NUM --testing $TESTING --exp_code $EXP_CODE
python train.py --config configs/$EXP_NUM/hexagon_abs.yml --cuda $CUDA_NUM --testing $TESTING --exp_code $EXP_CODE
python train.py --config configs/$EXP_NUM/hexagon_steel.yml --cuda $CUDA_NUM --testing $TESTING --exp_code $EXP_CODE
python train.py --config configs/$EXP_NUM/nut_pom.yml --cuda $CUDA_NUM --testing $TESTING --exp_code $EXP_CODE
python train.py --config configs/$EXP_NUM/nut_pp.yml --cuda $CUDA_NUM --testing $TESTING --exp_code $EXP_CODE
python train.py --config configs/$EXP_NUM/nut_acrylic.yml --cuda $CUDA_NUM --testing $TESTING --exp_code $EXP_CODE
python train.py --config configs/$EXP_NUM/nut_al.yml --cuda $CUDA_NUM --testing $TESTING --exp_code $EXP_CODE
python train.py --config configs/$EXP_NUM/nut_pvc.yml --cuda $CUDA_NUM --testing $TESTING --exp_code $EXP_CODE
python train.py --config configs/$EXP_NUM/nut_bakelite.yml --cuda $CUDA_NUM --testing $TESTING --exp_code $EXP_CODE
python train.py --config configs/$EXP_NUM/nut_cu.yml --cuda $CUDA_NUM --testing $TESTING --exp_code $EXP_CODE
python train.py --config configs/$EXP_NUM/nut_nylon.yml --cuda $CUDA_NUM --testing $TESTING --exp_code $EXP_CODE
python train.py --config configs/$EXP_NUM/nut_abs.yml --cuda $CUDA_NUM --testing $TESTING --exp_code $EXP_CODE
python train.py --config configs/$EXP_NUM/nut_steel.yml --cuda $CUDA_NUM --testing $TESTING --exp_code $EXP_CODE
python train.py --config configs/$EXP_NUM/pentagon_pom.yml --cuda $CUDA_NUM --testing $TESTING --exp_code $EXP_CODE
python train.py --config configs/$EXP_NUM/pentagon_pp.yml --cuda $CUDA_NUM --testing $TESTING --exp_code $EXP_CODE
python train.py --config configs/$EXP_NUM/pentagon_acrylic.yml --cuda $CUDA_NUM --testing $TESTING --exp_code $EXP_CODE
python train.py --config configs/$EXP_NUM/pentagon_al.yml --cuda $CUDA_NUM --testing $TESTING --exp_code $EXP_CODE
python train.py --config configs/$EXP_NUM/pentagon_pvc.yml --cuda $CUDA_NUM --testing $TESTING --exp_code $EXP_CODE
python train.py --config configs/$EXP_NUM/pentagon_bakelite.yml --cuda $CUDA_NUM --testing $TESTING --exp_code $EXP_CODE
python train.py --config configs/$EXP_NUM/pentagon_cu.yml --cuda $CUDA_NUM --testing $TESTING --exp_code $EXP_CODE
python train.py --config configs/$EXP_NUM/pentagon_nylon.yml --cuda $CUDA_NUM --testing $TESTING --exp_code $EXP_CODE
python train.py --config configs/$EXP_NUM/pentagon_abs.yml --cuda $CUDA_NUM --testing $TESTING --exp_code $EXP_CODE
python train.py --config configs/$EXP_NUM/pentagon_steel.yml --cuda $CUDA_NUM --testing $TESTING --exp_code $EXP_CODE
python train.py --config configs/$EXP_NUM/propeller_pom.yml --cuda $CUDA_NUM --testing $TESTING --exp_code $EXP_CODE
python train.py --config configs/$EXP_NUM/propeller_pp.yml --cuda $CUDA_NUM --testing $TESTING --exp_code $EXP_CODE
python train.py --config configs/$EXP_NUM/propeller_acrylic.yml --cuda $CUDA_NUM --testing $TESTING --exp_code $EXP_CODE
python train.py --config configs/$EXP_NUM/propeller_al.yml --cuda $CUDA_NUM --testing $TESTING --exp_code $EXP_CODE
python train.py --config configs/$EXP_NUM/propeller_pvc.yml --cuda $CUDA_NUM --testing $TESTING --exp_code $EXP_CODE
python train.py --config configs/$EXP_NUM/propeller_bakelite.yml --cuda $CUDA_NUM --testing $TESTING --exp_code $EXP_CODE
python train.py --config configs/$EXP_NUM/propeller_cu.yml --cuda $CUDA_NUM --testing $TESTING --exp_code $EXP_CODE
python train.py --config configs/$EXP_NUM/propeller_nylon.yml --cuda $CUDA_NUM --testing $TESTING --exp_code $EXP_CODE
python train.py --config configs/$EXP_NUM/propeller_abs.yml --cuda $CUDA_NUM --testing $TESTING --exp_code $EXP_CODE
python train.py --config configs/$EXP_NUM/propeller_steel.yml --cuda $CUDA_NUM --testing $TESTING --exp_code $EXP_CODE
python train.py --config configs/$EXP_NUM/spike_pom.yml --cuda $CUDA_NUM --testing $TESTING --exp_code $EXP_CODE
python train.py --config configs/$EXP_NUM/spike_pp.yml --cuda $CUDA_NUM --testing $TESTING --exp_code $EXP_CODE
python train.py --config configs/$EXP_NUM/spike_acrylic.yml --cuda $CUDA_NUM --testing $TESTING --exp_code $EXP_CODE
python train.py --config configs/$EXP_NUM/spike_al.yml --cuda $CUDA_NUM --testing $TESTING --exp_code $EXP_CODE
python train.py --config configs/$EXP_NUM/spike_pvc.yml --cuda $CUDA_NUM --testing $TESTING --exp_code $EXP_CODE
python train.py --config configs/$EXP_NUM/spike_bakelite.yml --cuda $CUDA_NUM --testing $TESTING --exp_code $EXP_CODE
python train.py --config configs/$EXP_NUM/spike_cu.yml --cuda $CUDA_NUM --testing $TESTING --exp_code $EXP_CODE
python train.py --config configs/$EXP_NUM/spike_nylon.yml --cuda $CUDA_NUM --testing $TESTING --exp_code $EXP_CODE
python train.py --config configs/$EXP_NUM/spike_abs.yml --cuda $CUDA_NUM --testing $TESTING --exp_code $EXP_CODE
python train.py --config configs/$EXP_NUM/spike_steel.yml --cuda $CUDA_NUM --testing $TESTING --exp_code $EXP_CODE
python train.py --config configs/$EXP_NUM/square_pom.yml --cuda $CUDA_NUM --testing $TESTING --exp_code $EXP_CODE
python train.py --config configs/$EXP_NUM/square_pp.yml --cuda $CUDA_NUM --testing $TESTING --exp_code $EXP_CODE
python train.py --config configs/$EXP_NUM/square_acrylic.yml --cuda $CUDA_NUM --testing $TESTING --exp_code $EXP_CODE
python train.py --config configs/$EXP_NUM/square_al.yml --cuda $CUDA_NUM --testing $TESTING --exp_code $EXP_CODE
python train.py --config configs/$EXP_NUM/square_pvc.yml --cuda $CUDA_NUM --testing $TESTING --exp_code $EXP_CODE
python train.py --config configs/$EXP_NUM/square_bakelite.yml --cuda $CUDA_NUM --testing $TESTING --exp_code $EXP_CODE
python train.py --config configs/$EXP_NUM/square_cu.yml --cuda $CUDA_NUM --testing $TESTING --exp_code $EXP_CODE
python train.py --config configs/$EXP_NUM/square_nylon.yml --cuda $CUDA_NUM --testing $TESTING --exp_code $EXP_CODE
python train.py --config configs/$EXP_NUM/square_abs.yml --cuda $CUDA_NUM --testing $TESTING --exp_code $EXP_CODE
python train.py --config configs/$EXP_NUM/square_steel.yml --cuda $CUDA_NUM --testing $TESTING --exp_code $EXP_CODE
python train.py --config configs/$EXP_NUM/turbine_pom.yml --cuda $CUDA_NUM --testing $TESTING --exp_code $EXP_CODE
python train.py --config configs/$EXP_NUM/turbine_pp.yml --cuda $CUDA_NUM --testing $TESTING --exp_code $EXP_CODE
python train.py --config configs/$EXP_NUM/turbine_acrylic.yml --cuda $CUDA_NUM --testing $TESTING --exp_code $EXP_CODE
python train.py --config configs/$EXP_NUM/turbine_al.yml --cuda $CUDA_NUM --testing $TESTING --exp_code $EXP_CODE
python train.py --config configs/$EXP_NUM/turbine_pvc.yml --cuda $CUDA_NUM --testing $TESTING --exp_code $EXP_CODE
python train.py --config configs/$EXP_NUM/turbine_bakelite.yml --cuda $CUDA_NUM --testing $TESTING --exp_code $EXP_CODE
python train.py --config configs/$EXP_NUM/turbine_cu.yml --cuda $CUDA_NUM --testing $TESTING --exp_code $EXP_CODE
python train.py --config configs/$EXP_NUM/turbine_nylon.yml --cuda $CUDA_NUM --testing $TESTING --exp_code $EXP_CODE
python train.py --config configs/$EXP_NUM/turbine_abs.yml --cuda $CUDA_NUM --testing $TESTING --exp_code $EXP_CODE
python train.py --config configs/$EXP_NUM/turbine_steel.yml --cuda $CUDA_NUM --testing $TESTING --exp_code $EXP_CODE
